# Generated by Django 4.2.5 on 2023-09-20 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finecap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
